variables:
  ${{ if eq(parameters.cudaEnabled, false) }}:
    displayName: 'Ubuntu ${{ parameters.ubuntuVersion }}'
  ${{ if eq(parameters.cudaEnabled, true) }}:
    displayName: 'Ubuntu ${{ parameters.ubuntuVersion }} (CUDA)'

parameters:
  ubuntuVersion: '18.04'
  cudaEnabled: false

jobs:
- job: ubuntu_build_${{ replace(parameters.ubuntuVersion, '.', '') }}_cuda_${{ parameters.cudaEnabled }}
  displayName: $(displayName)
  pool:
    vmImage: 'ubuntu-${{ parameters.ubuntuVersion }}'
  steps:
  - script: |
      sudo apt install -y \
        build-essential \
        ninja-build \
        libboost-program-options-dev \
        libboost-filesystem-dev \
        libboost-graph-dev \
        libboost-system-dev \
        libboost-test-dev \
        libeigen3-dev \
        libceres-dev \
        libfreeimage-dev \
        libgoogle-glog-dev \
        libgflags-dev \
        libglew-dev \
        qtbase5-dev \
        libqt5opengl5-dev \
        libcgal-dev \
        libcgal-qt5-dev \
        xvfb
      ${{ if eq(parameters.cudaEnabled, true) }}:
        sudo apt install -y nvidia-cuda-dev
    displayName: 'Install dependencies'

  - script: |
      cmake --version
      mkdir build
      cd build
      cmake .. \
        -GNinja \
        -DTESTS_ENABLED=ON
      ninja
    displayName: 'Configure and build'

  - script: |
      export DISPLAY=":99.0"
      export QT_QPA_PLATFORM="offscreen"
      Xvfb :99 &
      sleep 3
      cd build
      ctest
      tests_pass=$?
      if [ $tests_pass -ne 0 ]; then
          echo "Tests failed, rerunning with verbose output"
          ctest --rerun-failed --output-on-failure
      fi
      exit $tests_pass
    displayName: 'Run tests'
