trigger:
  - dev

jobs:
  - template: build-ubuntu.yaml
    parameters:
      ubuntuVersion: 18.04
  - template: build-ubuntu.yaml
    parameters:
      ubuntuVersion: 20.04
  - template: build-mac.yaml
