parameters:
  buildType: ubuntuVersion

jobs:
- job: ubuntu_build_${{ replace(parameters.ubuntuVersion, '.', '') }}
  displayName: 'Ubuntu ${{ parameters.ubuntuVersion }}'
  pool:
    vmImage: 'ubuntu-${{ parameters.ubuntuVersion }}'
  steps:
  - script: |
      sudo apt install -y \
        build-essential \
        ninja-build \
        libboost-program-options-dev \
        libboost-filesystem-dev \
        libboost-graph-dev \
        libboost-system-dev \
        libboost-test-dev \
        libeigen3-dev \
        libceres-dev \
        libfreeimage-dev \
        libgoogle-glog-dev \
        libgflags-dev \
        libglew-dev \
        qtbase5-dev \
        libqt5opengl5-dev \
        libcgal-dev \
        libcgal-qt5-dev \
        xvfb
    displayName: 'Install dependencies'

  - script: |
      cmake --version
      mkdir build
      cd build
      cmake .. \
        -GNinja \
        -DTESTS_ENABLED=ON
      ninja
    displayName: 'Configure and build'

  - script: |
      export DISPLAY=":99.0"
      sh -e /etc/init.d/xvfb start
      sleep 3
      cd build
      ctest
      tests_pass=$?
      if [ $tests_pass -ne 0 ]; then
          echo "\n\n\nTests failed, rerunning with verbose output"
          ctest --rerun-failed --output-on-failure
      fi
      exit $tests_pass
    displayName: 'Run tests'
