trigger:
  - dev

jobs:
  - template: build-ubuntu.yaml
    parameters:
      displayName: 'Ubuntu 18.04'
      ubuntuVersion: 18.04
  - template: build-ubuntu.yaml
    parameters:
      displayName: 'Ubuntu 20.04'
      ubuntuVersion: 20.04
  - template: build-ubuntu.yaml
    parameters:
      displayName: 'Ubuntu 20.04 (CUDA 10.1)'
      ubuntuVersion: 20.04
      cudaVersion: 10.1
  - template: build-mac.yaml
    parameters:
      displayName: 'Mac 10.15'
      macVersion: 10.15
