parameters:
  displayName: 'Ubuntu 18.04'
  ubuntuVersion: '18.04'
  cudaVersion: ''

jobs:
- job: ubuntu_build_${{ replace(parameters.ubuntuVersion, '.', '') }}_cuda_${{ replace(parameters.cudaVersion, '.', '') }}
  displayName: '${{ parameters.displayName }}'
  pool:
    vmImage: 'ubuntu-${{ parameters.ubuntuVersion }}'
  steps:
  - script: |
      sudo apt install -y \
        build-essential \
        ninja-build \
        libboost-program-options-dev \
        libboost-filesystem-dev \
        libboost-graph-dev \
        libboost-system-dev \
        libboost-test-dev \
        libeigen3-dev \
        libceres-dev \
        libfreeimage-dev \
        libgoogle-glog-dev \
        libgflags-dev \
        libglew-dev \
        qtbase5-dev \
        libqt5opengl5-dev \
        libcgal-dev \
        libcgal-qt5-dev \
        xvfb
    displayName: 'Install dependencies'
  
  - ${{ if not(eq(parameters.cudaVersion, '')) }}:
    - script: |
        ubuntu_version=${{ replace(parameters.ubuntuVersion, '.', '') }}
        cuda_version=${{ parameters.cudaVersion }}
        wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu${ubuntu_version}/x86_64/cuda-repo-ubuntu${ubuntu_version}_${cuda_version}_amd64.deb
        sudo dpkg -i cuda-repo-ubuntu${ubuntu_version}_${cuda_version}_amd64.deb
        sudo apt-get update -qq
        cuda_version_apt=${cuda_version:0:3}
        sudo apt-get install -y cuda-drivers cuda-core-${cuda_version_apt} cuda-cudart-dev-${cuda_version_apt} cuda-curand-dev-${cuda_version_apt}
        sudo ln -s /usr/local/cuda-${cuda_version:0:3}/ /usr/local/cuda
      displayName: 'Install CUDA'

  - script: |
      cmake --version
      mkdir build
      cd build
      cmake .. \
        -GNinja \
        -DTESTS_ENABLED=ON
      ninja
    displayName: 'Configure and build'

  - script: |
      export DISPLAY=":99.0"
      export QT_QPA_PLATFORM="offscreen"
      Xvfb :99 &
      sleep 3
      cd build
      ctest
      tests_pass=$?
      if [ $tests_pass -ne 0 ]; then
          echo "Tests failed, rerunning with verbose output"
          ctest --rerun-failed --output-on-failure
      fi
      exit $tests_pass
    displayName: 'Run tests'
