jobs:
- job: windows_build
  displayName: 'Windows VS2019'
  timeoutInMinutes: 240
  pool:
    vmImage: 'windows-2019'
  variables:
    vcpkgGitCommitId: ec6fe06e8da05a8157dc8581fa96b36b571c1bd5
  steps:
  - task: Cache@2
    displayName: 'Cache vcpkg'
    inputs:
      key: $(Build.SourcesDirectory)/.azure-pipelines/build-windows-vcpkg.txt | "$(vcpkgGitCommitId)" | "$(Agent.OS)"
      path: '$(Build.BinariesDirectory)/vcpkg'

  - task: run-vcpkg@0
    displayName: 'Run vcpkg'
    inputs:
      vcpkgArguments: '@$(Build.SourcesDirectory)/.azure-pipelines/build-windows-vcpkg.txt'
      vcpkgGitCommitId: $(vcpkgGitCommitId)
      vcpkgGitURL: https://github.com/microsoft/vcpkg

  - task: run-cmake@0
    displayName: 'Run CMake with Ninja'
    inputs:
      cmakeListsTxtPath: '$(Build.SourcesDirectory)/CMakeLists.txt'
      useVcpkgToolchainFile: true
      vcpkgTriplet: '$(RUNVCPKG_VCPKG_TRIPLET)'
