jobs:
- job: mac_build
  displayName: 'Mac 10.15'
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - script: |
      brew install \
        cmake \
        ninja \
        boost \
        eigen \
        freeimage \
        glog \
        gflags \
        ceres-solver \
        qt5 \
        glew \
        cgal
    displayName: 'Install dependencies'

  - script: |
      cmake --version
      mkdir build
      cd build
      cmake .. \
        -GNinja \
        -DTESTS_ENABLED=ON \
        -DQt5_DIR=/usr/local/opt/qt/lib/cmake/Qt5
      ninja
    displayName: 'Configure and build'

  - script: |
      Xvfb :99 &
      export DISPLAY=:99
      sleep 3
      cd build
      ctest
      tests_pass=$?
      if [ $tests_pass -ne 0 ]; then
          echo "\n\n\nTests failed, rerunning with verbose output"
          ctest --rerun-failed --output-on-failure
      fi
      exit $tests_pass
    displayName: 'Run tests'
